### PR TITLE
Create FAQ.md

### PR DESCRIPTION
**Pull request by tanju-b**
FAQ launch for Issue #19

### CODE REVIEW

**Comment by danawoodman** [comment]
@tanju-b thanks! Is this compiling for you into HTML? Right now we have no build process so you'd need to create a `faq.html` file with HTML in it for it to work. Lemme know if you need any assistance with that!

**Comment by placer14** [comment]
Actually, I don't think we've agreed to keep the HTML process. Before moving forward on this, I think we need to decide on our process before spinning more wheels. I would think we don't want contributors to have to produce HTML and would want a simpler format (like markdown?).

**Comment by danawoodman** [comment]
@placer14 I view getting content up priority 1 and then at the same time figuring out a longer term management process. HTML isn't ideal but the time to get a CMS/generator working shouldn't stop us from putting up content. Let's discuss the longer term plan on our NOM website call that is coming up

**Comment by tanju-b** [comment]
I simply created a markdown file to get the content going.  If you merge it, it will simply end up in the repo and github should render it same as the readme.md files... it won't show up on the main NOM page unless someone builds a link to it, etc.

If you don't want to merge this now, I guess that I can do an actual fork and build the FAQ.md out on the fork until it is better suited to merge?    ( I on a learning curve here with github and dev, but I am pretty comfortable with markdown)

this is what the FAQ.md looks like rendered by github:
https://github.com/tanju-b/nationofmakers.github.io/blob/master/FAQ.md

capture

**Comment by danawoodman** [comment]
@tanju-b thanks, I will merge for now and we can turn it to HTML for now, cheers

**Pull request merged**
